# Generated by Django 4.1.7 on 2023-07-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_book_give_back_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='give_back_request',
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='return_state_request',
            field=models.BooleanField(default=False),
        ),
    ]
